
package vista;
import com.mysql.cj.x.protobuf.MysqlxDatatypes;
import dao.UnidadFormativaDao;

import entidades.UnidadFormativa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author borda
 */
public class UnidadFormativaConsulta extends javax.swing.JFrame {
    
    //metodo para rellenar tabla
    
    public void RellenarTabla() throws SQLException{
        int horas = Integer.parseInt(txtHorasCon.getText()); // capturo el string que ocupa el campo txthoras y lo convierto en int
        UnidadFormativa uf = new UnidadFormativa(txtCodigoCon.getText(),txtDescripcionCon.getText(),horas); // creo un objeto de la clase UnidadFormativa y le doy los valores de la pantalla.
        
        UnidadFormativaDao ufd = new UnidadFormativaDao(); // creo un objeto de la clase UnidadFormativaDao
        
        ArrayList<UnidadFormativa> aluf = ufd.ConsultaUFDao(uf.getCodigo(), uf.getDescripcion()); // creo un arraylist y lo reyeno usando el metodo consulta de la clases UnidadFormativaDao pasandole los valores del objeto creado antes de UnidadFormativa.
                  
        DefaultTableModel modelo = new DefaultTableModel(); //creo un objeto tabla.
        
        //creo un bucle for para con el arraylist obtenido antes rellenar los campos de la tabla.
    
        for (int i = 0; i < aluf.size(); i++) {            
            modelo.addRow(new Object[]{aluf.get(i).getCodigo(),aluf.get(i).getDescripcion(),aluf.get(i).getHoras()});     // doy a cada objeto fila los valores del arraylist.       
        }
        
        try {
            ufd.ConsultaUFDao(uf.getCodigo(), uf.getDescripcion()); //revisar esta linea
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al realizar la busqueda seleccionada." + ex.getMessage());
        }     
        
        
    }

    /**
     * Creates new form UnidadFormativaConsulta
     */
    public UnidadFormativaConsulta() {
        initComponents();
        this.setLocationRelativeTo(null); // codigo para que aparezca le ventana en el centro de la pantalla.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigoCon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnidadesFormativasCon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcionCon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHorasCon = new javax.swing.JTextField();
        btnBuscarCon = new javax.swing.JButton();
        btnNuevoCon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONSULTA Y BUSQUEDA DE UNIDADES FORMATIVAS");
        setResizable(false);

        jLabel1.setText("Código");

        tblUnidadesFormativasCon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Horas"
            }
        ));
        tblUnidadesFormativasCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUnidadesFormativasConMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUnidadesFormativasCon);

        jLabel2.setText("Descripcion");

        jLabel3.setText("Horas");

        btnBuscarCon.setText("BUSCAR");
        btnBuscarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConActionPerformed(evt);
            }
        });

        btnNuevoCon.setText("NUEVO");
        btnNuevoCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoConActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoCon)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCon))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtHorasCon)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcionCon, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcionCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHorasCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCon)
                    .addComponent(btnNuevoCon))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConActionPerformed
        try {
            RellenarTabla();            
        } catch (SQLException ex) {
            Logger.getLogger(UnidadFormativaConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarConActionPerformed

    private void btnNuevoConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoConActionPerformed
        int horas = Integer.parseInt(txtHorasCon.getText());
        UnidadFormativa uf = new UnidadFormativa(txtCodigoCon.getText(),txtDescripcionCon.getText(),horas);
        
        UnidadFormativaDao ufd = new UnidadFormativaDao();
        
        try {
            ufd.AñadirUFDao(uf);
        } catch (SQLException ex) {
            Logger.getLogger(UnidadFormativaConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevoConActionPerformed

    private void tblUnidadesFormativasConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUnidadesFormativasConMouseClicked
        
        int filaseleccionada = tblUnidadesFormativasCon.rowAtPoint(evt.getPoint());
        //idjuego.setText(tabla.getValueAt(filaseleccionada, 0).toString());
        String cod = String.valueOf(tblUnidadesFormativasCon.getValueAt(filaseleccionada,0));
        String des = String.valueOf(tblUnidadesFormativasCon.getValueAt(filaseleccionada,1));
        String hor = String.valueOf(tblUnidadesFormativasCon.getValueAt(filaseleccionada,2));
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnidadFormativaEdicion(cod,des,hor).setVisible(true);
            }
        });

    }//GEN-LAST:event_tblUnidadesFormativasConMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UnidadFormativaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UnidadFormativaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UnidadFormativaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UnidadFormativaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UnidadFormativaConsulta().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCon;
    private javax.swing.JButton btnNuevoCon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUnidadesFormativasCon;
    private javax.swing.JTextField txtCodigoCon;
    private javax.swing.JTextField txtDescripcionCon;
    private javax.swing.JTextField txtHorasCon;
    // End of variables declaration//GEN-END:variables
}
